# Generated by Django 5.1.5 on 2025-06-25 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='images/album_previews')),
                ('shown', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.profile')),
                ('images', models.ManyToManyField(blank=True, to='home.image')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tag')),
            ],
        ),
    ]
